name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ "win-x64", "linux-x64" ]

    runs-on: ubuntu-latest

    env:
      Solution_Name: SIT.Manager.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
            
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Get build date
      id: build
      shell: pwsh
      run: |
        $CurrentTime = Get-Date -Format 'yyMM'
        $BuildTime = Get-Date -Format 'ddHH'
        Write-Output "NOW=$CurrentTime" >> $env:GITHUB_OUTPUT
        Write-Output "VERSION=$BuildTime" >> $env:GITHUB_OUTPUT 
        
    - name: Build Published Version
      run: dotnet publish SIT.Manager.Desktop/SIT.Manager.Desktop.csproj -c Release -r ${{ matrix.os }} -p:BuildNumber=${{ steps.build.outputs.NOW }} -p:RevisionNumber=${{ steps.build.outputs.VERSION }}

    - name: Compress on Windows
      if: ${{ matrix.os == 'win-x64' }}
      run: |
        zip -r ${{ matrix.os }}.zip ${{ github.workspace }}/SIT.Manager.Desktop/bin/Release/net8.0/${{ matrix.os }}/publish/*
  
    - name: Compress on Linux
      if: ${{ matrix.os == 'linux-x64' }}
      run: |
        tar -czvf ${{ matrix.os }}.tar.gz ${{ github.workspace }}/SIT.Manager.Desktop/bin/Release/net8.0/${{ matrix.os }}/publish/*

    # Create release as draft from the compressed file(s)
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          draft: true
          generate_release_notes: true
          files: ${{ github.workspace }}/SIT.Manager.Desktop/bin/Release/net8.0/${{ matrix.os }}/publish/${{ matrix.os }}.*
          tag_name: ManagerReleaseTest2