name: .NET Core Desktop for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Build Debug
      run: dotnet build -c Debug -p:BuildNumber=8859 -p:RevisionNumber=32229
      
    - name: Build Release
      run: dotnet publish -c Release -p:BuildNumber=8859 -p:RevisionNumber=32229
    
    - name: Package releaseFile
      run: Compress-Archive -Path D:\a\SIT.Manager.Avalonia\SIT.Manager.Avalonia\SIT.Manager.Desktop\bin\${{ matrix.configuration }}\net8.0\win-x64\* -Destination ${{ matrix.configuration }}.zip

    - name: Upload Built Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: |
          ${{ matrix.configuration }}.zip
