name: .NET Core Desktop for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager.sln
    strategy:
      matrix:
        configuration: [Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: cl

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Get build date
      id: build
      shell: pwsh
      run: |
        $CurrentTime = Get-Date -Format 'yyyyMMddHHmmss'
        $BuildTime = Get-Date -Format '2.yyyy.MMdd.HHmmss'
        Write-Output "NOW=$CurrentTime" >> $env:GITHUB_OUTPUT
        Write-Output "VERSION=$BuildTime" >> $env:GITHUB_OUTPUT        
        
    - name: Build Solution
      run: |
        dotnet build --configuration ${{ matrix.configuration }}
        dotnet pack ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} /p:FileVersion=${{ steps.build.outputs.VERSION }} /p:Version=2-${{ matrix.configuration }}-${{ steps.build.outputs.NOW }}        
        
    - name: Package File
      run: Compress-Archive -Path ${{ github.workspace }}/SIT.Manager.Desktop/bin/${{ matrix.configuration }}/net8.0/win-x64/* -Destination ${{ matrix.configuration }}.zip
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ matrix.configuration }}
        path: ${{ github.workspace }}/${{ matrix.configuration }}.zip
        if-no-files-found: error
        retention-days: 3
