name: .NET Core Desktop for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: SIT.Manager
    strategy:
      matrix:
        configuration: [Debug, Release]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        
    - name: Get build date
      id: build
      shell: pwsh
      run: |
        $CurrentTime = Get-Date -Format 'yyyyMMddHHmmss'
        $BuildTime = Get-Date -Format '1.yyyy.MMdd.HHmmss'
        Write-Output "NOW=$CurrentTime" >> $env:GITHUB_OUTPUT
        Write-Output "VERSION=$BuildTime" >> $env:GITHUB_OUTPUT        
        

    - name: Build Solution
      run: |
        dotnet build --configuration ${{ matrix.configuration }}
        dotnet pack ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} /p:FileVersion=1.0.0.0 /p:Version=1.0.0-${{ matrix.configuration }}-${{ steps.build.outputs.NOW }}        
        
    - name: Package releaseFile
      run: Compress-Archive -Path D:\a\SIT.Manager.Avalonia\SIT.Manager.Avalonia\SIT.Manager.Desktop\bin\${{ matrix.configuration }}\net8.0\win-x64\* -Destination ${{ matrix.configuration }}.zip

    - name: Upload Built Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration }}
        path: |
          ${{ matrix.configuration }}.zip
        retention-days: 3
